### ISSUE TITLE
Uninstallation script is not deleting the installation dir

### ISSUE THREAD

**Issue by jamshed-khan** [rcschaff82/cwp_dnsreport#3]
I uninstalled the script and then tried to reinstall it and it failed due to the error "fatal: destination path 'cwp_dnsreport' already exists and is not an empty directory."

So, your uninstallation script should delete the cwp_dnsreport dir too.

**Comment by rcschaff82** [comment]
Added Directions to the Uninstall Script to manual remove if not intending to update.
