### ISSUE TITLE
Not working in latest version of cwp

### ISSUE THREAD

**Issue by prakash76101** [rcschaff82/cwp_dnsreport#4]
Warning: include_once(update_class.php): failed to open stream: No such file or directory in /usr/local/cwpsrv/htdocs/resources/admin/modules/dnsreport/header.php on line 12

Warning: include_once(): Failed opening 'update_class.php' for inclusion (include_path='.:/usr/local/cwp/php71/lib/php') in /usr/local/cwpsrv/htdocs/resources/admin/modules/dnsreport/header.php on line 12

Fatal error: Uncaught Error: Class 'gitupdate' not found in /usr/local/cwpsrv/htdocs/resources/admin/modules/dnsreport/header.php:13 Stack trace: #0 /usr/local/cwpsrv/htdocs/resources/admin/modules/dnsreport/index.php(3): include_once() #1 /usr/local/cwpsrv/htdocs/admin/admin/index.php(0): unknown() #2 {main} thrown in /usr/local/cwpsrv/htdocs/resources/admin/modules/dnsreport/header.php on line 13

**Comment by rcschaff82** [comment]
The issue has been corrected.  I put the class file in the wrong path.
