### ISSUE TITLE
Reg: New feature Request in CWP For mail 

### ISSUE THREAD

**Issue by prakash76101** [rcschaff82/cwp_dnsreport#6]
Hi

Hope you are doing well 

i have a request for email tracelog for cwp right now there is only one option where we can see the mailog of postfix there is no feature for mail log tracing the mails sent and recd in specific domain or all domain (In cpanel the option is already there for years) If you can do a plugin like the dns report/2fa will be more useful for users like me to track emails sent and recd

**Comment by rcschaff82** [comment]
Any chance you can post some screenshots.  It's been forever since I used Cpanel

**Comment by prakash76101** [comment]
[aaaa.pdf](https://github.com/rcschaff82/cwp_dnsreport/files/4718962/aaaa.pdf)
Pls see the report taken in cpanel which gives a log report that the email send or recd is sent to thier server or not ...

there will be four options to filter
1.show successes
2. Show deferred
3.show failures
4. show in progress

in the report it show the status from email id/to email id , spam score from spamassian, recipient address , sent /recd time, result in action button its how the details of server and mail accepted or deferred etc...
this modue is bery much needed in cwp to ensure all the legitimate emails are recd and spam emails are filtered
